version: "3"
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports: 
      - "443:443"
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./db/:/var/lib/mysql/
networks:
  internal:
    driver: bridge
