version: "3"
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    networks:
      - internal
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - internal
networks:
  internal:
    driver: bridge
