version: "3"
services:

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports: 
      - "443:443"
    networks:
      - internal
    volumes:
      - wpfiles:/var/www/html
    restart: always
    depends_on:
        - wordpress
        - mariadb

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - internal
    volumes:
      - wpfiles:/var/www/html
    restart: always
    depends_on:
        - mariadb
    env_file:
      - .env

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - sqldb:/var/lib/mysql
    restart: always
    env_file:
      - .env

volumes:

  sqldb:
    driver: local
    driver_opts:
      type: none
      device: /home/swillis/data/sqldb
      o: bind
  wpfiles:
    driver: local
    driver_opts:
      type: none
      device: /home/swillis/data/wpfiles
      o: bind

networks:
  internal:
    driver: bridge
