version: "3"
services:

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports: 
      - "443:443"
    networks:
      - internal
    volumes:
      - ./files/:/var/www/html/
    restart: always
    depends_on:
        - mariadb
        - wordpress

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./files/:/var/www/html/
    restart: always
    depends_on:
        - mariadb
    env_file:
      - .env

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./db/:/var/lib/mysql/
    restart: always
    env_file:
      - .env

networks:
  internal:
    driver: bridge
