version: "3"
services:

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports: 
      - "443:443"
    networks:
      - internal
    volumes:
      - wpfiles:/var/www/html
    restart: always
    depends_on:
        - wordpress

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - wpfiles:/var/www/html
    restart: always
    depends_on:
        - mariadb
    env_file:
      - .env

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - sqldb:/var/lib/mysql
    restart: always
    env_file:
      - .env

volumes:

  sqldb:
    driver: local
    driver_opts:
      type: none
      device: /home/swillis/data/sqldb
      o: bind
  wpfiles:
    driver: local
    driver_opts:
      type: none
      device: /home/swillis/data/wpfiles
      o: bind

networks:
  internal:
    driver: bridge
